version: "3.8"

services:
  psql-db2:
    image: postgres
    container_name: psql-db2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=VitalTrack
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d VitalTrack" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend-service:
    image: backend-service:latest  # Sử dụng image đã build trước đó
    container_name: backend-service
    ports:
      - '8080:8080' # Ánh xạ cổng: 8083 là cổng host, 8075 là cổng container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db2:5432/VitalTrack
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      psql-db2:
        condition: service_healthy
    volumes:
      - ./src:/app  # Mount volume nếu cần
